optimizer : 'diag_ekf'     # optimizer type: 'quad_prog', 'sgd', 'diag_ekf', 'dense_ekf'
num_replay_update : 20     # how many prior replay updates to do during the update
max_buffer_length : 2000   # max replay buffer length for the recursive estimator
