kinova:
  type: robot
  file_name: !relative_path ../../knowledge/robot_model/kinova_gen3.urdf
punyo:
  type: deformable
  file_name: !relative_path ../../knowledge/robot_model/punyo_mesh_partial.ply
  parent_name: EndEffector_Link
  parent_relative_transform: [[0.0, -1.0, 0.0, 0.0], [0.34202014, 0.0, -0.93969262, 0.02111], 
                              [0.93969262, 0.0, 0.34202014, 0.096142], [0.0, 0.0, 0.0, 1.0]]


