# demo simulation / estimation configuration for use with point_vsf_estimate.py

world: !include worlds/kinova_world.yaml
# world: !include worlds/kinova_punyo_world.yaml

simulator:
  type: quasistatic
  deformables:
    vsf:
      model:
        type: point
        ### CHANGE HERE: PATH TO EMPTRY VSF FILE NAME ###
        path: !relative_path ../demo_data/saved_vsfs/rubber_fig_tall_angle00/vsf_empty.npz
        # path: !relative_path ../demo_data/saved_vsfs/white_nike_angle00/vsf_empty.npz
      config:
        friction_mu: 0.5
        sim_slide: False
        slide_step: 0.0001

sensors:
  kinova_joint_torques: !include sensors/kinova_joint_torques.yaml
  # punyo_pressure: !include sensors/punyo_pressure.yaml

calibrators:
  kinova_joint_torques:
    type: tare
    num_samples: 20
  # punyo_pressure:
  #   type: tare
  #   num_samples: 10

#uncomment to train on subset
#train_sequences: [0]
#test_sequences: [0]

### CHANGE HERE: PATH TO DATASET DIRECTORY ###
dataset: !include ../demo_data/datasets/joint_torques_dataset_config.yaml
# dataset: !include ../demo_data/datasets/punyo_pressure_dataset_config.yaml

estimator: !include "estimators/quad_prog.yaml"
# estimator: !include "estimators/sgd.yaml"
# estimator: !include "estimators/diag_ekf.yaml"

prior:
  type: gaussian
  mu: 0.0
  var: 100.0
