dataset:
    smoothing: 20
    type: punyo
    path: /media/motion/shaoxiong/punyo_tmp_data/arm_data/brown_columbia_angle02_trail1
    keys: !include datasets/kinova_punyo_postprocessed_keys.yaml
    sensor_keys:
        kinova_joint_torques : torques

world: !include "worlds/kinova_punyo_world.yaml"

sensors:
    kinova_joint_torques: !include sensors/kinova_joint_torques.yaml

calibrators:
  kinova_joint_torques:
    type: tare
    num_samples: 20

simulator:
    type: quasistatic
    deformables:
        vsf:
            type: neural
            model:
                database_file_name: ../knowledge/vsf_database/small_object_params.json
                num_layers: 8
                hidden_dim: 64
                skip_connection: [4]
            config:
                N_samples: 100
                volume_unit: 10000

optimization:
    learning_rate: 0.0005
    max_iterations: 20000