dataset:
    type: punyo
    path: !relative_path ../demo_data/data2
    keys: !include datasets/kinova_punyo_postprocessed_keys.yaml

    control_keys:
        punyo: punyo_curr_pts
    sensor_keys:
        punyo: punyo_force
        
world: !include worlds/punyo_world.yaml

sensors:
    punyo: !include sensors/punyo_force.yaml

calibrators:
    punyo:
        type: tare
        num_samples: 20

simulator:
    type: quasistatic
    deformables:
        vsf:
            type: neural
            init_method: from_mesh
            path: !relative_path ../demo_data/data2/meta_data/mesh.obj
            model:
                num_layers: 8
                hidden_dim: 64
                skip_connection: [4]
            config:
                N_samples: 100
                volume_unit: 10000

optimization:
    learning_rate: 0.0005
    max_iterations: 20000